apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        # Placeholder: CI will replace 'latest' with the Git SHA
        image: prodmicroserviceplatformregistry.azurecr.io/auth-service:a242a9ceebff3bdba9b2ee834999ac12d9f334db
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: acr-pull-secret