apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    release: monitoring-stack
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001