apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: prodmicroserviceplatformregistry.azurecr.io/gateway:a5144d6c6d3e175fc408e75b362ba4f26495408e
        imagePullPolicy: Always
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.default.svc.cluster.local:80"
        - name: TASKS_SERVICE_URL
          value: "http://tasks-service.default.svc.cluster.local:80"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-pull-secret