apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: prodmicroserviceplatformregistry.azurecr.io/gateway:9868adcf2aaff2886931be03a1a3a339e072ca0d
        imagePullPolicy: Always
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.default.svc.cluster.local"
        - name: TASKS_SERVICE_URL
          value: "http://tasks-service.default.svc.cluster.local"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-pull-secret