apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 80