apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    release: monitoring-stack
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 