apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  labels:
    app: tasks-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
      - name: tasks-service
        image: prodmicroserviceplatformregistry.azurecr.io/tasks-service:a6b667f140cc189e824fbb637a5813626c802206
        imagePullPolicy: Always
      imagePullSecrets:
      - name: acr-pull-secret
        ports:
        - containerPort: 5000