apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  labels:
    app: tasks-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
      - name: tasks-service
        image: prodmicroserviceplatformregistry.azurecr.io/tasks-service:db57522cbde71faa45697da60b12bfc36c31479e
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
      imagePullSecrets:
      - name: acr-pull-secret