apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elaa-brahmi/microservice-gitops
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true # This ensures it finds auth-service, gateway, and tasks-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated:
      prune: true    # Deletes resources if you remove them from Git
      selfHeal: true # Fixes manual changes made to the cluster